import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'},],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Welcome 👋🏻'
        },
        {
          type: 'doc',
          id: 'intro/working-with-our-api',
          label: 'Working with our API'
        },
        {
          type: 'doc',
          id: 'intro/before-you-start',
          label: 'Before you start'
        },
        {
          type: 'link',
          label: 'API Reference',
          href: '/restful-api-reference/',
        },
        {
          type: 'link',
          label: 'Help Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Account',
      items: [
        {
          type: 'doc',
          id: 'account/your-account',
          label: 'Your Account'
        },
        {
          type: 'doc',
          id: 'account/api-keys',
          label: 'API Keys'
        }
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      items: [
        {
          type: 'doc',
          id: 'sdk/javascript',
          label: 'JavaScript SDK'
        },
        {
          type: 'doc',
          id: 'sdk/java',
          label: 'Java SDK'
        },
        {
          type: 'doc',
          id: 'sdk/php',
          label: 'PHP SDK'
        },
        {
          type: 'doc',
          id: 'sdk/dart',
          label: 'Dart SDK'
        },
        {
          type: 'doc',
          id: 'sdk/android',
          label: 'Android SDK'
        },
        {
          type: 'doc',
          id: 'sdk/ios',
          label: 'iOS SDK'
        },
      ],
    },
    {
      type: 'category',
      label: 'Entities',
      items: [
        {
          type: 'doc',
          id: 'entities/overview',
          label: 'Entities Overview'
        },
        {
          type: 'doc',
          id: 'entities/creating',
          label: 'Creating Entities'
        },
      ],
    },
    {
      type: 'category',
      label: 'Rules',
      items: [
        {
          type: 'doc',
          id: 'rules/overview',
          label: 'Rules Overview'
        },
        {
          type: 'doc',
          id: 'rules/creating',
          label: 'Creating Rules'
        },
      ],
    },
    {
      type: 'category',
      label: 'Events',
      items: [
        {
          type: 'doc',
          id: 'events/overview',
          label: 'Events Overview'
        },
        {
          type: 'doc',
          id: 'events/creating',
          label: 'Creating Events'
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrate',
      items: [
        {
          type: 'doc',
          id: 'integrate/custom-webhook',
          label: 'Custom WebHook'
        },
        {
          type: 'doc',
          id: 'integrate/zapier',
          label: 'Zapier'
        },
        {
          type: 'doc',
          id: 'integrate/outlook-calendar',
          label: 'Outlook Calendar'
        },
        {
          type: 'doc',
          id: 'integrate/google-calendar',
          label: 'Google Calendar'
        },
      ],
    },
  ],
};

export default sidebars;
