import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'},],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Welcome 👋🏻'
        },
        {
          type: 'doc',
          id: 'intro/working-with-our-api',
          label: 'Working with our API'
        },
        {
          type: 'doc',
          id: 'intro/before-you-start',
          label: 'Before you start'
        },
        {
          type: 'link',
          label: 'API Reference',
          href: '/docs/restful-api-reference/',
        },
        {
          type: 'link',
          label: 'Help Center',
          href: 'https://example.com',
        },
      ],
    },
    {
      type: 'category',
      label: 'Account',
      items: [
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Your Account'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'API Keys'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Test & Live Mode'
        },
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      items: [
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'JavaScript SDK'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Java SDK'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'PHP SDK'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Flutter SDK'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Android SDK'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'iOS SDK'
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrate',
      items: [
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Custom WebHook'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Zapier'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Outlook Calendar'
        },
        {
          type: 'doc',
          id: 'intro/welcome',
          label: 'Google Calendar'
        },
      ],
    },
  ],
};

export default sidebars;
